/* CODE GENERATED BY BEHAVIOUR TOOL */

#include "b_fight"

// main will be called by a verb when it has been completed, through ExecuteScript.
void main()
{
    int iBehaviour = GetLocalInt(GetModule(), "curr_behaviour");
    int iReturn = getVerbReturn(iBehaviour);
    int iVerb = getVerbFinished(iBehaviour);

    if (iReturn == SUCCESS)
    {
        control_Fight(iBehaviour, iVerb);
    }
    else
    {
        timeout_Fight(iBehaviour);
    }
}